import type { NextApiRequest, NextPage } from "next";
import { connect } from "../utils/connection";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const HashPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Link-it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Requested link not found</h1>
      </main>
    </div>
  );
};

export async function getServerSideProps(request: NextApiRequest) {
  const { linkId } = request.query;
  const { ShortLink } = await connect(); // connect to database
  const fullData = await ShortLink.findOneAndUpdate(
    { short: linkId },
    { $inc: { clicks: 1 } },
    { projection: { full: 1, _id: 0 } }
  );

  if (fullData) {
    return {
      redirect: {
        destination: fullData.full,
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
}

export default HashPage;
