import type { NextApiRequest, NextPage } from "next";
import Head from "next/head";
const { API_URL } = process.env;

const HashPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Link-it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-bold">
        <h1>Requested link not found</h1>
      </main>
    </div>
  );
};

export async function getServerSideProps(request: NextApiRequest) {
  const { linkId } = request.query;
  try {
    const response = await fetch(`${API_URL}/${linkId}`);
    const fullData = await response.json();
    if (fullData && fullData.full) {
      return {
        redirect: {
          destination: fullData.full,
          permanent: false,
        },
      };
    }
    return {
      props: {},
    };
  } catch (c) {
    console.log(c);
    return {
      props: {},
    };
  }
}

export default HashPage;
