import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Link from "next/link";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="relative min-h-screen py-8 bg-gray-100 font-body px:4 sm:px-24 lg:px-32 xl:px-40">
      <Head>
        <title>Link-it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-between items-baseline p-4 font-bold">
        <h2 className="text-2xl text-blue-600 ">
          <Link href="./">Link-it</Link>
        </h2>
        <div className="text-gray-500 underline">
          <Link href="./viewLinks">View all links</Link>
        </div>
      </nav>
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
