import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
const { API_URL } = process.env;

const Home: NextPage = (props) => {
  const [url, setUrlValue] = useState("");
  const [shortUrl, setShortUrl] = useState("");
  const handleSubmit = async (e: HTMLFormElement) => {
    e.preventDefault();
    if (url.length > 0) {
      try {
        const response = await fetch(`${props.apiUrl}/createLink`, {
          method: "post",
          body: JSON.stringify({ full: url }),
        });
        const fullData = await response.json();
        if (fullData.short) {
          setShortUrl(fullData.short);
        }
      } catch (c) {}
    }
  };
  const resultLink = props.apiUrl.split("/api")[0] + "/" + shortUrl;
  return (
    <div className="">
      <Head>
        <title>Link-it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-between items-baseline p-4 font-bold">
        <h2 className="text-2xl text-blue-600 ">Link -it</h2>
        <div className="text-gray-500 underline">
          <Link href="./view-all-links">View all links</Link>
        </div>
      </nav>
      <main className="p-4 pt-0">
        <p className="text-xl font-bold text-gray-600">Welcome to Link-it!</p>
        <p className="font-bold text-gray-400">Only Link shortener you need</p>
        <form
          className="flex flex-col items-center justify-center mt-16"
          onSubmit={handleSubmit}
        >
          <label className="sr-only">Shorten your url</label>
          <input
            placeholder="Enter URL to shorten"
            type="url"
            required
            autoFocus
            value={url}
            onChange={(e) => setUrlValue(e.target.value)}
            className="text-grey-darkest rounded-md outline outline-4 outline-blue-600 p-2"
          ></input>
          {shortUrl && (
            <a
              href={resultLink}
              className="text-xl text-blue-600 pt-5 underline"
            >
              {resultLink}
            </a>
          )}
        </form>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  return {
    props: { apiUrl: API_URL },
  };
}

export default Home;
